modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="vminus"
version="3.2.3"
displayName="VMinus"
displayURL="https://curseforge.com/minecraft/mc-mods/v-minus"
logoFile="logo.png"
authors="lixir"
description="Edit and Remove Items, Blocks, Entities, Enchantments & more with Configs / Datapacks!"

[[dependencies.vminus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



