modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="vminus"
version="3.3.1"
displayName="VMinus"
displayURL="https://curseforge.com/minecraft/mc-mods/vminus"
logoFile="logo.png"
authors="lixir"
description="Edit, Replace, and Remove Items, Blocks, Entities and more with Configs / Datapacks!"

[[dependencies.vminus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.vminus]]
    modId="forge"
    mandatory=true
    versionRange="[47.3.22,)"
    ordering="NONE"
    side="BOTH"


